apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: azure-example
  namespace: dev
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-global
  target:
    name: global-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: example-externalsecret-key
