apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: azure-example
  namespace: default
spec:
  refreshInterval: 15s
  secretStoreRef:
    kind: SecretStore
    name: azure-local
  target:
    name: local-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: example-externalsecret-key
