apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: azure-local
  namespace: default
spec:
  provider:
    azurekv:
      tenantId: bc51f07b-c08c-47ac-901c-b803790d62be
      vaultUrl: "https://gfc-eso-vault-example.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-secret
          key: ClientID
        clientSecret:
          name: azure-secret
          key: ClientSecret
